# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QMainWindow, QPushButton, QApplication


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(286, 130)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(13, 10, 261, 61))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 80, 131, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удаление элемента"))
        self.textEdit.setHtml(_translate("Dialog",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//"
                                         "EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" />"
                                         "<style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\';"
                                         "font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px;"
                                         "margin-left:0px; margin-right:0px; -qt-block-indent:0;"
                                         "text-indent:0px;\"><span style=\" font-family:\'Arial\';"
                                         "font-size:12pt; color:#aa0000;\">Вы уверены, что хотите </span></p>\n"
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px;"
                                         "margin-left:0px; margin-right:0px; -qt-block-indent:0;"
                                         "text-indent:0px;\"><span style=\" font-family:\'Arial\';font-size:12pt;"
                                         "color:#aa0000;\">удалить выделенный(-e) элемент?</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "OK"))


class DeleteDialog(QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.accepted = 0
        self.pushButton.clicked.connect(self.get_data)

    def get_data(self):
        self.accepted = 1
        self.accept()

    def exec_(self):
        super(DeleteDialog, self).exec_()
        if self.accepted:
            return 1
        else:
            return 0


def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == "__main__":
    class Window(QMainWindow):
        def __init__(self):
            super().__init__()
            self.centralWidget = QPushButton("test")
            self.centralWidget.clicked.connect(self.film_testing)
            self.setCentralWidget(self.centralWidget)

        def film_testing(self):
            dlg = DeleteDialog()
            print(dlg.exec_())


    app = QApplication(sys.argv)
    win = Window()
    win.show()
    sys.excepthook = except_hook
    sys.exit(app.exec())