# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genre_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QMainWindow, QPushButton, QApplication


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(16, 19, 111, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(104, 80, 151, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название"))
        self.pushButton.setText(_translate("Dialog", "Сохранить изменения"))


class GenreAddDialog(QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("Добавление жанра")
        self.accepted = 0
        self.pushButton.clicked.connect(self.get_data)

    def get_data(self):
        self.title = self.lineEdit.text()
        self.accepted = 1
        self.accept()

    def exec_(self):
        super(GenreAddDialog, self).exec_()
        if self.accepted:
            return 1, self.title
        else:
            return 0,


class GenreEditDialog(GenreAddDialog):
    def __init__(self, title):
        super().__init__()
        self.setWindowTitle("Редактирование жанра")
        self.lineEdit.setText(title)


def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == "__main__":
    class Window(QMainWindow):
        def __init__(self):
            super().__init__()
            self.centralWidget = QPushButton("test")
            self.centralWidget.clicked.connect(self.film_testing)
            self.setCentralWidget(self.centralWidget)

        def film_testing(self):
            dlg = GenreAddDialog()
            print(dlg.exec_())


    app = QApplication(sys.argv)
    win = Window()
    win.show()
    sys.excepthook = except_hook
    sys.exit(app.exec())
